config/routes.rb
Tpv::Application.routes.draw do
  resources :tickets

  get "home/index"
  resources :items
  resources :categories
  resources :bills do
   resources :items
  end

  
  
  resources :tables do
     resource :bill
  end
  resources :products do
   resources :items
  end
  
  match 'items/:id/plus' => 'items#plus',:as=>:plus
  match 'items/:id/minus' => 'items#minus',:as=>:minus

 

   root :to => 'home#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
 has_many :items,:dependent=>:destroy
 belongs_to :table,:foreign_key=>'table_id'
 has_one :ticket,:dependent=>:destroy
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  layout 'sell',:only=>:show

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render :json => @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @categories=Category.all
    @bill = Bill.find(params[:id])
    @products=Product.all
    
    respond_to do |format|
      format.html
     # format.js { head :no_content }
     end    
  end

  # GET /bills/new
  # GET /bills/new.json
  
  
  def new
    @table=Table.find(params[:id])
    @categories=Category.all
   
    @bill=Bill.create
    @bill.table=@table
    #@bill = Bill.new
    @bill.save
    
    redirect_to @bill
    #respond_to do |format|
    #  format.html # new.html.erb
    #  format.json { render :json => @bill }
    #end
  end

  # GET /bills/1/edit
  def edit
     @categories=Category.all
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    
    @bill = Bill.params([:bill])
    #@bill.table_id=params[:id]
    puts '..........................'
    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, :notice => 'Bill was successfully created.' }
        format.json { render :json => @bill, :status => :created, :location => @bill }
      else
        format.html { render :action => "new" }
        format.json { render :json => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to @bill, :notice => 'Creada la nueva cuenta' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<div class="clearfix">
   <%= f.label :name, t("activerecord.attributes.bill.description", :default => "Descripción"), :class => :label %>
  <div class="input">
    <%= f.text_field :description, :class => 'text_field' %>
  </div>
</div>
<div class="clearfix">
   <%= f.label :table, t("activerecord.attributes.bill.table", :default => "Mesa"), :class => :label %>
  <div class="input">
    <%= f.select :table_id, Table.all.collect {|t| [ t.name, t.id ] }, {:include_blank => 'Ninguna'},:class => 'text_field',:height=>'20px' %>
  </div>
</div>

<div class="form-actions">
  <button class="btn primary" type="submit">Guardar</button> o
	<%= link_to "Cancelar", products_path %>
</div>

app/views/bills/_modal.html.erb
<div class="modal hide fade" id="modal-window">
  <div class="modal-header">
    <a href="#" class="close">×</a>
    <h3>Loading...</h3>
  </div>
  <div class="modal-body center">
      <%= image_tag "loading.gif" %>
  </div>
  <div class="modal-footer">&nbsp;</div>
</div>

app/views/bills/edit.html.erb
<%= form_for @bill, :url => bill_path(@bill), :html => { :class => "edit_bill", :id => "edit_bill" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/bills/index.html.erb
<h1>Cuentas</h1>
<br/>
<ul class="breadcrumb">
  <li >
   <%=link_to 'Mesas',tables_path%> <span class="divider">/</span>
  </li>
  <li class='active'>
   <%=link_to 'Cuentas',bills_path%> <span class="divider">/</span>
  </li>
  
</ul>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Mesa / Descripción</th>
      <th>Emitida</th>
      <th>Estado</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
         <td><%if !bill.table.nil?%><%= bill.table.name%><%end%>  <%= bill.description %></td>
        <td><%= l bill.created_at,:format=>:short  %></td>
        <td> 
        <%if bill.status==false%>Pendiente
 		<%else%>Pagada<%end%>
 		</td>
        <td>
          <%= link_to bill_path(bill) ,:class=>"btn  btn-success" do %>
     	 <i class="icon-eye-open "></i> Ver
	  <% end %>
          <%= link_to 'Editar', edit_bill_path(bill), :class => 'btn ' %>
          <%= link_to 'Borrar', bill_path(bill), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger'%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!--<%= render :file=>'shared/modal'%>-->
<!--<%= link_to 'Cuenta nueva', new_bill_path, :class => 'btn btn-primary btn-large' %>-->

app/views/bills/new.html.erb
<%= form_for @bill, :url => bills_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/bills/show.html.erb
<%if !@bill.table.nil?%>
<h1>Cuenta: <%=@bill.table.name%></h1>
<%else%>
<h1>Cuenta: <%=@bill.ticket.table%></h1>
<%end%>


<br/>
<ul class="breadcrumb">
   <li >
   <%=link_to 'Mesas',tables_path%> <span class="divider">/</span>
  </li>
   <li >
   <%if !@bill.table.nil?%>
   <%=link_to @bill.table.name,table_path(@bill.table)%> 
   <span class="divider">/</span>
   <%else%>
   
   <%end%>
   
  </li>
  <li >
 
<li class="active">
      <%=link_to 'Cuenta'%>
  </li>
  
</ul>
<!--
<label class='label'>Mesa </label>
	<p><b>Mesa       :</b> <%if !@bill.table.nil?%><%= @bill.table.name %><%else%>Sin mesa asignada<%end%></p>
	<p><b>Descripción:</b> <%if @bill.description!=''%><%= @bill.description %><%else%>Sin descripción<%end%></p>
-->


<label class="label"><%= t("activerecord.attributes.bill.created_at", :default => t("activerecord.labels.created_at", :default => "Emitida")) %>:</label>
<p><%= l @bill.created_at,:format=>:short %></p>
<label class="label"><%= t("activerecord.attributes.bill.tatus", :default => t("activerecord.labels.status", :default => "Estado")) %>:</label>
<p>
 <%if @bill.status==false%> 
  	<a href="<%=new_ticket_path(:id=>@bill)%>" class="btn btn-danger" rel="popover" data-content="Haga clic en el enlace para crear el ticket de la cuenta" data-original-title="Atención">Pendiente</a>
 <%else%>
  	<a href="#" class="btn btn-info" rel="popover" data-content="Haga clic en el enlace para cambiar el estado de la cuenta" data-original-title="Atención">Pagada</a>
 <%end%>
</p>

<label class="label">Productos</label>
<div id='items'>
<%= render :partial=>'shared/items',:locals=>{:bill=>@bill}%>
</div>

<div class="form-actions">
<%= link_to "Volver a mesas", tables_path, :class => 'btn'  %>
<a href="<%=edit_bill_path(@bill)%>" class="btn btn-info" rel="popover" data-content="Este botón permite editar la cuenta y trasladarla a otra mesa, asi como añadir la descripción" data-original-title="Edición">Editar</a>

<%= link_to "Borrar", bill_path(@bill), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>