config/routes.rb
Tpv::Application.routes.draw do
  resources :tickets

  get "home/index"
  resources :items
  resources :categories
  resources :bills do
   resources :items
  end

  
  
  resources :tables do
     resource :bill
  end
  resources :products do
   resources :items
  end
  
  match 'items/:id/plus' => 'items#plus',:as=>:plus
  match 'items/:id/minus' => 'items#minus',:as=>:minus

 

   root :to => 'home#index'

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
 
  def index
    @tables = Table.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, :notice => 'Table was successfully created.' }
        format.json { render :json => @table, :status => :created, :location => @table }
      else
        format.html { render :action => "new" }
        format.json { render :json => @table.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, :notice => 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @table.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_for @table, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Table</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', tables_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/tables/index.html.erb
<h1>Mesas</h1>
<br/>
<ul class="breadcrumb">
  <li >
   <%=link_to 'Mesas',tables_path%> <span class="divider">/</span>
  </li>
  <li class='active'>
   <%=link_to 'Cuentas',bills_path%> <span class="divider">/</span>
  </li>
  
</ul>

<table class="table table-condensed">
  <thead>
    <tr>
     
      <th>Nombre</th>
      <th>Cuenta</th>
      <th>Estado</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tables.each do |table| %>
      <tr>
       
        <td><%= table.name%></td>
      
      <td>
      	<%if table.bill.nil?%>
          <%=link_to new_bill_path(:id=>table),:class=>'btn' do %>
     	  <i class="icon-plus "></i> Abrir cuenta<% end %>
      	<%else%>
      	   <%=link_to bill_path(table.bill),:class=>'btn' do %>
     	  <i class="icon-eye-open "></i>    Ver cuenta<% end %>
      	<%end%>
      </td>
      
      <td>
        <%if !table.bill.nil?%>
 		<%if table.bill.status==false%><span class="label label-important">Pendiente</span>
 		<%else%><span class="label label-success">Pagada</span><%end%>
	    <%end%>
	  </td>
      
        <td>
          <%= link_to 'Editar', edit_table_path(table), :class => 'btn' %>
          <%= link_to 'Borrar', table_path(table), :method => :delete, :confirm => '¿Seguro? NO se puede deshacer', :class => 'btn  btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nueva mesa', new_table_path, :class => 'btn btn-primary btn-large' %>

app/views/tables/show.html.erb
<h1>Mesa </h1>

<label class="label">Nombre</label>
<p><%= @table.name %></p>
<label class="label">Cuenta</label>
<p><%if @table.bill.status==false%><span class="label label-important">Pendiente</span>
<%else%><span class="label label-success">Pagada</span><%end%><p>
<p><b>Importe:</b> <%=number_to_currency(total(@table.bill),:unit =>'€',:format => "%n %u")%></p>

<p><%= link_to 'Ver cuenta',@table.bill ,:class=>'btn'%></p>

<div class="form-actions">
  <%= link_to 'Volver', tables_path, :class => 'btn btn-large'  %>
  &nbsp;&nbsp;&nbsp;
  <%= link_to 'Editar', edit_table_path(@table), :class => 'btn btn-large' %>
  &nbsp;&nbsp;&nbsp;
  <%= link_to 'Delete', table_path(@table), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger btn-large' %>
</div>