config/routes.rb
Tpv::Application.routes.draw do
  resources :tickets

  get "home/index"
  resources :items
  resources :categories
  resources :bills do
   resources :items
  end

  
  
  resources :tables do
     resource :bill
  end
  resources :products do
   resources :items
  end
  
  match 'items/:id/plus' => 'items#plus',:as=>:plus
  match 'items/:id/minus' => 'items#minus',:as=>:minus

 

   root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, :notice => 'Category was successfully created.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, :notice => 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Category</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', categories_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/categories/index.html.erb
<h1>Categorys</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= link_to category.name, category_path(category) %></td>
        <td><%= category.created_at %></td>
        <td>
          <%= link_to 'Editar', edit_category_path(category), :class => 'btn btn' %>
          <%= link_to 'Eliminar', category_path(category), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_category_path, :class => 'btn btn-primary' %>

app/views/categories/show.html.erb
<h1>Category</h1>

<p>
  <b>Name</b><br>
  <%= @category.name %>
</p>

<div class="form-actions">
  <%= link_to 'Back', categories_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_category_path(@category), :class => 'btn' %>
  <%= link_to 'Delete', category_path(@category), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>