config/routes.rb
Tpv::Application.routes.draw do
  resources :tickets

  get "home/index"
  resources :items
  resources :categories
  resources :bills do
   resources :items
  end

  
  
  resources :tables do
     resource :bill
  end
  resources :products do
   resources :items
  end
  
  match 'items/:id/plus' => 'items#plus',:as=>:plus
  match 'items/:id/minus' => 'items#minus',:as=>:minus

 

   root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tpv</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
      
        <%=link_to 'Bar Alfalfa',root_path,:class=>'brand'%>
        <div class="nav-collapse">
          <ul class="nav"> 
            <li><%= link_to "Mesas",tables_path %></li>
            <li><%= link_to "Cuentas", bills_path %></li>
            <li><%= link_to "Examinar productos", products_path %></li>           
            <li><%= link_to "Categorias",categories_path%></li>
            <li><%= link_to "Cart" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span8"><%= yield %></div>
      <div class="span4">
        <h2>Opciones Generales</h2>
       <br/>
       <p><%=link_to 'Mesas',tables_path,:class=>'btn btn-large'%></p>
       <p><%=link_to 'Cuentas',bills_path,:class=>'btn btn-large'%></p>
       <p><%=link_to 'Productos',products_path,:class=>'btn btn-large'%></p>
       <p><%=link_to 'Categorias',categories_path,:class=>'btn btn-large'%></p>
        <p><%=link_to 'Tickets',tickets_path,:class=>'btn btn-large'%></p>
       
     
      </div>
    
    </div>
  </div>
</body>

</body>
</html>

app/views/layouts/guest.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tpv</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class='row'>
 <div class="span2 offset1"><%= image_tag('enrailsblack.jpg',:size=>'100x100')%></div>
</div>
<div class="navbar navbar-fixed-top"> 
    <div class="navbar-inner">
    
      <div class="container">
         
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        
        <a class="brand" href="#">Bar Alfalfa</a>
        <div class="nav-collapse">
          <ul class="nav"> 
          
          </ul>
          
        </div>
       
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span4"><p></p></div>
      <div class="span4"><%= yield %></div>
      <div class="span4">
              <!-- 
        	<h2>About Us</h2>
       		Texto que se muestra en el lateral, jugar con las anchuras
       		Cuando @bill no nulo carga las opciones de productos-->
          	<%= render :file=>"shared/acordeon"%>
      	</div>
    
    </div>
  </div>
</body>

</body>
</html>

app/views/layouts/sell.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tpv</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
      
        <%=link_to 'Bar Alfalfa',root_path,:class=>'brand'%>
        <div class="nav-collapse">
          <ul class="nav"> 
            <li><%= link_to "Mesas",tables_path %></li>
            <li><%= link_to "Cuentas", bills_path %></li>
            <li><%= link_to "Examinar productos", products_path %></li>           
            <li><%= link_to "Categorias",categories_path%></li>
            <li><%= link_to "Cart" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span6"><%= yield %></div>
      <div class="span6">
       
       <!-- 
        <h2>About Us</h2>
       Texto que se muestra en el lateral, jugar con las anchuras
     
        
        Cuando @bill no nulo carga las opciones de productos-->
          <%= render :file=>"shared/acordeon"%>
      </div>
    
    </div>
  </div>
</body>

</body>
</html>